language: node_js

sudo: required

node_js:
    - 8.11.3

cache:
  directories:
    - node_modules

env:

  global:

    - GH_REF: github.com/sakyawang/sakyawang.github.com.git

branches:

  only:

    - hexo-source

before_install:
  - npm install -g hexo-cli

install:
  - npm install
  
script:

  - hexo clean

  - hexo g

after_script:

  - cp -rf CNAME ./public

  - cp -rf google5ecb77d99c95160a.html ./public   

  - cd public

  - git init

  - git config user.name "wanghao0319072@gmail.com"

  - git config user.email "wanghao0319072@gmail.com"

  - git add .

  - git commit -m "update blog"

  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}"  master:master
